"""
LLM Composer - TARDIS Symphony
Uses OpenRouter API to compose Minimalist Piano sheet music based on TARDIS Harmony.
"""
import requests
import json
import os

# API Configuration
API_KEY = "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"
API_URL = "https://openrouter.ai/api/v1/chat/completions"
MODEL = "xiaomi/mimo-v2-flash:free"

def compose_partiture():
    print("🤖 Contacting the Cosmic Composer (OpenRouter)...")
    
    # The Prompt - Defining the "TARDIS Mode"
    prompt = """
    You are a Neoclassical Composer (like Erik Satie or Philip Glass).
    Compose a short PIANO piece called "The TARDIS Resonance".
    
    RULES:
    1. Key: A Minor (Am).
    2. Harmony: Use the "AAGOOCH" chord progression (Am9 -> Am7 -> G -> Bdim).
    3. Style: Minimalist, repetitive arithmetic arpeggios.
    4. Atmosphere: Mysterious, Cosmic, Ethereal.
    
    OUTPUT FORMAT:
    Return ONLY valid ABC Notation (standard music notation code). 
    Start with X:1 and include the header fields (T, M, K, L, Q).
    Do not include markdown blocks or explanations. Just the ABC code.
    """

    try:
        response = requests.post(
            url=API_URL,
            headers={
                "Authorization": f"Bearer {API_KEY}",
                "Content-Type": "application/json",
                "HTTP-Referer": "https://tardis-project.com", 
                "X-Title": "TARDIS Decoded"
            },
            data=json.dumps({
                "model": MODEL,
                "messages": [
                    {"role": "system", "content": "You are a music composition engine that outputs ABC Notation."},
                    {"role": "user", "content": prompt}
                ]
            })
        )
        
        if response.status_code == 200:
            result = response.json()
            content = result['choices'][0]['message']['content']
            
            # Clean up response (sometimes LLMs add markdown code blocks)
            abc_code = content.replace("```abc", "").replace("```", "").strip()
            
            print("✅ Composition Received!")
            return abc_code
        else:
            print(f"❌ API Error: {response.status_code} - {response.text}")
            return None

    except Exception as e:
        print(f"❌ Connection Error: {e}")
        return None

def generate_html(abc_code):
    html_template = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <title>TARDIS Symphony: The Resonance</title>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/abcjs/6.2.2/abcjs-basic-min.js"></script>
        <style>
            body {{ font-family: 'Helvetica Neue', sans-serif; background: #0f0f15; color: #e0e0e0; text-align: center; padding: 20px; }}
            h1 {{ color: #a0a0ff; letter-spacing: 5px; text-transform: uppercase; }}
            .paper {{ background: #fff; padding: 20px; border-radius: 5px; max-width: 1000px; margin: 0 auto; color: #000; }}
            .info {{ margin-top: 20px; font-size: 0.9em; color: #888; }}
        </style>
    </head>
    <body>
        <h1>The TARDIS Resonance</h1>
        <p>Generated by A.I. anchored to the AAGOOCH Harmonic Scale</p>
        
        <div id="paper" class="paper"></div>
        
        <div class="info">
            <p>Mode: Minimalist Piano | Tuning: Symbolic (Requires 117Hz Calibration)</p>
        </div>

        <script type="text/javascript">
            var abc = `{abc_code}`;
            ABCJS.renderAbc("paper", abc, {{ responsive: "resize" }});
        </script>
    </body>
    </html>
    """
    return html_template

if __name__ == "__main__":
    abc_data = compose_partiture()
    if abc_data:
        # Save input for reference
        with open("Validation/tardis_score.abc", "w") as f:
            f.write(abc_data)
            
        # Generate HTML
        html_content = generate_html(abc_data)
        output_path = "../../DECODIFICANDO/06_LINGUISTICA/partitura_cosmica.html"
        
        # Ensure dir exists
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        
        with open(output_path, "w") as f:
            f.write(html_content)
        print(f"✅ HTML Generated: {output_path}")
    else:
        # Fallback if API fails (Deterministic Backup)
        print("⚠️ Using Deterministic Backup Score...")
        backup_abc = """X:1
T:The TARDIS Resonance (Backup)
C:TARDIS AI
M:4/4
L:1/8
Q:1/4=60
K:Am
|: "Am9"A,2 E2 B2 c2 | "Am7"G,2 E2 G2 B2 | "G"G,,2 D2 G2 B2 | "Bdim"B,,2 D2 F2 A2 :|
| "Am"A,,8 |]"""
        
        html_content = generate_html(backup_abc)
        output_path = "../../DECODIFICANDO/06_LINGUISTICA/partitura_cosmica.html"
        with open(output_path, "w") as f:
            f.write(html_content)
        print(f"✅ Backup HTML Generated: {output_path}")
